GA 2.0.0 release (#19)
Develop branch is ready for publication.

---------

Co-authored-by: silabs-akosj <146345861+silabs-akosj@users.noreply.github.com>

diff --git a/.github/workflows/00-Check-Code-Convention.yml b/.github/workflows/00-Check-Code-Convention.yml
--- a/.github/workflows/00-Check-Code-Convention.yml
+++ b/.github/workflows/00-Check-Code-Convention.yml
@@ -1,4 +1,4 @@
-name: Pre Commit check
+name: 00-Check-Code-Convention
 on:
   push:
     branches-ignore:
@@ -7,6 +7,7 @@ on:
   pull_request:
     branches:
       - main
+      - develop
       - "release/**"
   workflow_dispatch:
     inputs:
@@ -87,3 +88,14 @@ jobs:
         name: CodingConventionResult
         path: CodingConventionTool.txt
         retention-days: 90
+    - name: Check log file to set status of the job
+      run: |
+        keywords=("Failed")
+        for keyword in "${keywords[@]}"; do
+          if grep -q "$keyword" CodingConventionTool.txt; then
+            echo "Keyword '$keyword' found in the file."
+            exit 1
+          else
+            echo "Keyword '$keyword' not found in the file."
+          fi
+        done
